### PR TITLE
Client fixes

### PR DESCRIPTION
**Pull request by Ogaday**
Minor changes to the `Client` class. The main point is just a small usability feature so that if you update the token attribute of your `client` instance then the new token is propagated to the endpoints too. Otherwise the behaviour might be confusing.

### CODE REVIEW

**Comment by odinuv** [comment]
wouldn't it be better to forbid changing the token at all? changing it doesn't make sense to me, plus the client is not immutable then

**Comment by odinuv** [comment]
btw, you're still making PRs from `Ogaday` fork

**Comment by Ogaday** [comment]
> wouldn't it be better to forbid changing the token at all? changing it doesn't make sense to me, plus the client is not immutable then

I don't see the issue but it would be easy enough to do: I can simply delete lines 38 and below. I can make a new commit?

**Comment by odinuv** [comment]
the client is stateless except for the token and url, i.e if i write:
```
c = client(url, token)
c.create_bucket('some-bucket')
# snip unlimited amount of code
c.delete_bucket('some-bucket')
```

it's crystal clear what happens, however when i write:

```
c = client(url, token)
c.create_bucket('some-bucket')
c.token = token2
# snip unlimited amount of code
c.delete_bucket('some-bucket') # <- chaos, did it delete the created bucket or some other bucket? dependes whether token and token2 belong to same project and have same permissions
```

so i wouldn't like to promote the second usage, especially when it is completely unnecessary (or so i think).

**Comment by pivnicek** [comment]
yeah, I agree with Odin on this one.  Allowing to switch token for a client seems like it could enable some bad practices.
With one token per client, it becomes more obvious which token is doing what
```
client_a = client(url, tokenA)
client_a.create_bucket('some-bucket')

client_b = client(url, tokenB)
client_b.create_bucket('some-bucket')
```

**Comment by Ogaday** [comment]
That makes sense: updated.

**Pull request merged**
