### PR TITLE
Merge master into dev

### PR DESCRIPTION
**Pull request by Ogaday**
Merging master into dev so we can continue to develop on dev

### CODE REVIEW

**Comment by odinuv** [comment]
I'd like to delete the `dev` branch altogether and use small feature branches for whatever you like to do

**Comment by Ogaday** [comment]
So the workflow is that I create a feature branch on my own fork, then when the feature is ready for review I create a pull request from that branch on my fork to the master branch of the upstream repository?

That's fine for me.

**Comment by odinuv** [comment]
you can create branches straight from master in this repository

**Comment by Ogaday** [comment]
Do you mean like:

```bash
git checkout upstream/master && git checkout -b new-feature
```

Then I can implement new features on top of the most recent changes?

**Comment by pivnicek** [comment]
This is what I do:
```
git clone https://github.com/keboola/sapi-python-client.git
git checkout master
git pull
git checkout -b myNewFeature
** work on branch myNewFeature **
git push origin myNewFeature:myNewFeature
```
then the myNewFeature branch is available here to be a PR to master

**Comment by odinuv** [comment]
yes, that's the smallest number of steps i think :)

**Comment by Ogaday** [comment]
Cool. Either way, I'll make pull requests directly to master from now on.

**Pull request closed without merging**
